### ISSUE TITLE
Change formatting at runtime

### ISSUE THREAD

**Issue by krnlde** [baumandm/angular-numeraljs#15]
Inspired by i18next/ng-i18next, I like to be able to change the `.setCurrentLanguage()` at runtime. The i18next directive even changes all piped tokens after changing the language.

See this for reference: https://github.com/i18next/ng-i18next/blob/master/src/provider.js
How do I achieve this in your directive?

**Comment by DominicBoettger** [comment]
+1

**Comment by krnlde** [comment]
This project seems dead.

**Comment by DominicBoettger** [comment]
Okay, i had a look at the sources and i think i will recreate something like this in the next time....

**Comment by baumandm** [comment]
Hey, I apologize for letting this issue languish for so long.  I've released an update that adds support for reconfiguring at runtime via an injectable service.  There's a new [example](examples/changeLanguages/index.html) and a section in the README about it.  Let me know if anything is missing.

**Comment by DominicBoettger** [comment]
Hey @baumandm. Thanks you VERY much for this new version. It fixed my problems and works very good!
