### ISSUE TITLE
The latest version problem on npm

### ISSUE THREAD

**Issue by emmy41124** [baumandm/angular-numeraljs#24]
Hello @baumandm ,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
I downloaded the latest version v1.3.1, but I found the version description of `angular-numeraljs.js` which downloaded from npm were wrong, and the version description is still v1.2.0. Could you update the latest version description on npm?
Thanks very much!

[cdnjs/cdnjs#10086](https://github.com/cdnjs/cdnjs/pull/10086)

**Comment by baumandm** [comment]
Hi @emmy41124, sorry things got a bit out of sync.  I've published a new version 1.3.2 which has the correct headers.  Can you please update to that version.

**Comment by emmy41124** [comment]
Thanks for your help!
