### ISSUE TITLE
numeraljs 2

### ISSUE THREAD

**Issue by Deadly0** [baumandm/angular-numeraljs#25]
Is it works with Numeral.js v.2? Or v1 is still prefered?

**Comment by baumandm** [comment]
Hi @Deadly0, I haven't tested this with Numeral.js v2 yet, so I'm not sure if it's a simple drop-in replacement or if it will require substantial changes.  I'll try to look into it this weekend.

**Comment by baumandm** [comment]
I've just released a new version (2.0.0) for Numeral.js 2.x.  There are a few breaking changes in both Numeral.js and this library, so please check the README or CHANGELOG for details.
